facebook:
  client:
    clientId: 384261248599251
    clientSecret: fd7fa1c5f5a267f463263a0ce7ff2025
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
google:
  client:
    clientId: 737759673720-d9p8m68anni8rr40fgltfpqsceumh03i.apps.googleusercontent.com
    clientSecret: Mp69tNddiMEhMNYaiNCCR-kM
    accessTokenUri: https://www.googleapis.com/oauth2/v3/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    clientAuthenticationScheme: form
    scope: profile
  resource:
    userInfoUri: https://www.googleapis.com/userinfo/v2/me

server:
  port: 3000
  

         